apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: test-sc-name
provisioner: pd.csi.storage.gke.io
parameters:
  type: "hyperdisk-balanced"
  provisioned-iops-on-create: "3000"
  provisioned-throughput-on-create: "150Mi"
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: storage.k8s.io/v1alpha1
kind: VolumeAttributesClass
metadata:
  name: silver
driverName: pd.csi.storage.gke.io
parameters:
  iops: "3000"
  throughput: "150"
---
apiVersion: storage.k8s.io/v1alpha1
kind: VolumeAttributesClass
metadata:
  name: gold
driverName: pd.csi.storage.gke.io
parameters:
  iops: "3013"
  throughput: "151"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pv-claim
spec:
  storageClassName: test-sc-name
  volumeAttributesClassName: silver
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 64Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  volumes:
  - name: vol
    persistentVolumeClaim:
      claimName: test-pv-claim
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: "/vol"
      name: vol
