apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: balanced-pvc
spec:
  volumeAttributesClassName: gold
  storageClassName: balanced
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Gi
